---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: csi-plugin-controller-vpa
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: alicloud-csi-diskplugin
      controlledValues: RequestsOnly
    - containerName: alicloud-csi-provisioner
      controlledValues: RequestsOnly
    - containerName: alicloud-csi-attacher
      controlledValues: RequestsOnly
    - containerName: alicloud-csi-snapshotter
      controlledValues: RequestsOnly
    - containerName: alicloud-csi-resizer
      controlledValues: RequestsOnly
    - containerName: alicloud-csi-liveness-probe
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csi-plugin-controller
  updatePolicy:
    updateMode: Auto
