apiVersion: v1
kind: Service
metadata:
  name: csi-snapshot-validation
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-all-webhook-targets-allowed-ports: '[{"protocol":"TCP","port":443}]'
    {{- if and .Values.csiSnapshotValidationWebhook.topologyAwareRoutingEnabled (semverCompare "< 1.31-0" .Capabilities.KubeVersion.Version) }}
    service.kubernetes.io/topology-mode: "auto"
    {{- end }}
  labels:
    {{- if and .Values.csiSnapshotValidationWebhook.topologyAwareRoutingEnabled (semverCompare "< 1.32-0" .Capabilities.KubeVersion.Version) }}
    endpoint-slice-hints.resources.gardener.cloud/consider: "true"
    {{- end }}
spec:
  selector:
    app: snapshot-validation
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  {{- if and .Values.csiSnapshotValidationWebhook.topologyAwareRoutingEnabled (semverCompare ">= 1.31-0" .Capabilities.KubeVersion.Version) }}
  trafficDistribution: PreferClose
  {{- end }}
