---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--alicloud
  labels:
#    backup.gardener.cloud/provider: alicloud
#    seed.gardener.cloud/provider: alicloud
    shoot.gardener.cloud/provider: alicloud
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--alicloud
type: Opaque
data:
  accessKeyID: Zm9v # foo
  accessKeySecret: YmFy # bar
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--alicloud
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Shoot
    spec:
      networking:
        pods: 10.250.0.0/19
      kubernetes:
        version: 1.28.2
      hibernation:
        enabled: false
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: ControlPlane
metadata:
  name: control-plane
  namespace: shoot--foobar--alicloud
spec:
  type: alicloud
  region: eu-west-1
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--alicloud
  providerConfig:
    apiVersion: alicloud.provider.extensions.gardener.cloud/v1alpha1
    kind: ControlPlaneConfig
  # cloudControllerManager:
  #   featureGates:
  #     SomeKubernetesFeature: true
  infrastructureProviderStatus:
    apiVersion: alicloud.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    vpc:
      id: vpc-1234
      vswitches:
      - id: vswitch-acbd1234
        purpose: nodes
        zone: eu-west-1a
