---
apiVersion: v1
kind: Secret
metadata:
  name: dnsrecord-external
  namespace: shoot--foobar--alicloud
type: Opaque
data:
  ACCESS_KEY_ID: base64(access-key-id)
  ACCESS_KEY_SECRET: base64(access-key-secret)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--alicloud
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Shoot
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: DNSRecord
metadata:
  name: dnsrecord-external
  namespace: shoot--foobar--alicloud
spec:
  type: alicloud-dns
  secretRef:
    name: dnsrecord-external
    namespace: shoot--foobar--alicloud
# zone: example.com
  name: api.alicloud.foobar.shoot.example.com
  recordType: A # Use A, CNAME, or TXT
  values: # list of IP addresses for A records, a single hostname for CNAME records, or a list of texts for TXT records.
  - 1.2.3.4
# ttl: 120
