apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
  name: provider-alicloud
spec:
  deployment:
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/admission-alicloud-runtime:v1.66.1
      virtualCluster:
        helm:
          ociRepository:
            ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/admission-alicloud-application:v1.66.1
    extension:
      helm:
        ociRepository:
          ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/provider-alicloud:v1.66.1
      injectGardenKubeconfig: true
  resources:
  - kind: BackupBucket
    type: alicloud
  - kind: BackupEntry
    type: alicloud
  - kind: Bastion
    type: alicloud
  - kind: ControlPlane
    type: alicloud
  - kind: DNSRecord
    type: alicloud-dns
  - kind: Infrastructure
    type: alicloud
  - kind: Worker
    type: alicloud
