apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  config.yaml: |
    ---
    apiVersion: alicloud.provider.extensions.config.gardener.cloud/v1alpha1
    kind: ControllerConfiguration
{{- if .Values.config.clientConnection }}
    clientConnection:
      acceptContentTypes: {{ required ".Values.config.clientConnection.acceptContentTypes is required" .Values.config.clientConnection.acceptContentTypes }}
      contentType: {{ required ".Values.config.clientConnection.contentType is required" .Values.config.clientConnection.contentType }}
      qps: {{ required ".Values.config.clientConnection.qps is required" .Values.config.clientConnection.qps }}
      burst: {{ required ".Values.config.clientConnection.burst is required" .Values.config.clientConnection.burst }}
{{- end }}
{{- if .Values.config.machineImageOwnerSecret }}
    machineImageOwnerSecretRef:
      name: {{ .Values.config.machineImageOwnerSecret.name }}
      namespace: {{ .Release.Namespace }}
{{- end }}
    service:
      backendLoadBalancerSpec: {{ .Values.config.service.backendLoadBalancerSpec }}
{{- if .Values.config.toBeSharedImageIDs }}
    toBeSharedImageIDs:
    {{- range .Values.config.toBeSharedImageIDs }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
{{- if .Values.config.csi }}
    csi:
      enableADController: {{ .Values.config.csi.enableADController }}
{{- end }}
    etcd:
      storage:
        className: {{ .Values.config.etcd.storage.className }}
        capacity: {{ .Values.config.etcd.storage.capacity }}
{{- if .Values.config.etcd.backup }}
{{ toYaml .Values.config.etcd.backup | indent 6 }}
{{- end }}
