{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.labels }}
  labels:
{{ toYaml $machineClass.labels | indent 4 }}
{{- end }}
type: Opaque
data:
  userData: {{ $machineClass.secret.userData | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- if $machineClass.labels }}
{{ toYaml $machineClass.labels | indent 4 }}
    {{- end }}
    {{- if $machineClass.operatingSystem }}
{{ toYaml $machineClass.operatingSystem | indent 4 }}
    {{- end }}
{{- if $machineClass.nodeTemplate }}
nodeTemplate:
  architecture: {{ $machineClass.nodeTemplate.architecture }}
  capacity:
{{ toYaml $machineClass.nodeTemplate.capacity | indent 4 }}
  instanceType: {{ $machineClass.nodeTemplate.instanceType }}
  region: {{ $machineClass.nodeTemplate.region }}
  zone: {{ $machineClass.nodeTemplate.zone }}
{{- end }}
providerSpec:
  imageID: {{ $machineClass.imageID }}
  instanceType: {{ $machineClass.instanceType }}
  region: {{ $machineClass.region }}
  zoneID: {{ $machineClass.zoneID }}
  securityGroupID: {{ $machineClass.securityGroupID }}
  vSwitchID: {{ $machineClass.vSwitchID }}
  systemDisk:
    category: {{ $machineClass.systemDisk.category }}
    size: {{ $machineClass.systemDisk.size }}
{{- if $machineClass.dataDisks }}
  dataDisks:
{{ toYaml $machineClass.dataDisks | indent 2 }}
{{- end }}
  instanceChargeType: {{ $machineClass.instanceChargeType }}
  internetChargeType: {{ $machineClass.internetChargeType }}
  internetMaxBandwidthIn: {{ $machineClass.internetMaxBandwidthIn }}
  spotStrategy: {{ $machineClass.spotStrategy }}
  keyPairName: {{ $machineClass.keyPairName }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
secretRef:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
credentialsSecretRef:
  name: {{ $machineClass.credentialsSecretRef.name }}
  namespace: {{ $machineClass.credentialsSecretRef.namespace }}
provider: "Alicloud"
{{- end }}
