apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-alicloud
spec:
  deployment:
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/admission-alicloud-runtime:v1.65.1-dev
      virtualCluster:
        helm:
          ociRepository:
            ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/admission-alicloud-application:v1.65.1-dev
    extension:
      helm:
        ociRepository:
          ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/provider-alicloud:v1.65.1-dev
      injectGardenKubeconfig: true
  resources:
  - kind: BackupBucket
    type: alicloud
  - kind: BackupEntry
    type: alicloud
  - kind: Bastion
    type: alicloud
  - kind: ControlPlane
    type: alicloud
  - kind: DNSRecord
    type: alicloud
  - kind: Infrastructure
    type: alicloud
  - kind: Worker
    type: alicloud
