alicloud:
  region: cn-beijing

clusterName: test-namespace

sshPublicKey: sshkey-12345

vpc:
  create: true
  id: alicloud_vpc.vpc.id
  cidr: 10.10.10.10/6

natGateway:
  id: alicloud_nat_gateway.nat_gateway.id
  sNatTableIDs: alicloud_nat_gateway.nat_gateway.snat_table_ids

eip:
  internetChargeType: PayByTraffic

zones:
- name: cn-beijing-a
  cidr:
    workers: 10.250.0.0/19
#  eipAllocationID: eip-ufxsdg122elmszcg
- name: cn-beijing-b
  cidr:
    workers: 10.250.100.0/19

names:
  configuration: shoot.tf-config
  variables: shoot.tf-vars
  state: shoot.tf-state

initializeEmptyState: true

outputKeys:
  securityGroupID: sg_id
  vpcID: vpc_id
  vpcCIDR: vpc_cidr
  keyPairName: key_pair_name
  vswitchNodesPrefix: vswitch_z
