apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: cloud-controller-manager
    high-availability-config.resources.gardener.cloud/type: controller
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kubernetes
      role: cloud-controller-manager
  template:
    metadata:
      annotations:
        checksum/secret-cloud-provider-config: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        gardener.cloud/role: controlplane
        app: kubernetes
        role: cloud-controller-manager
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-alicloud-networks: allowed
        networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      automountServiceAccountToken: false
      priorityClassName: gardener-system-300
      containers:
      - name: alicloud-cloud-controller-manager
        image: {{ index .Values.images "alicloud-controller-manager" }}
        imagePullPolicy: IfNotPresent
        command:
        - /cloud-controller-manager
        - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        - --allow-untagged-cloud=true
        - --allocate-node-cidrs=true
        - --cloud-provider=alicloud
        - --leader-elect=true
        - --cluster-cidr={{ .Values.podNetwork }}
        - --use-service-account-credentials=false
        - --v=2
        - --cloud-config=/etc/kubernetes/cloudprovider/cloudprovider.conf
        - --cluster-name={{ .Values.clusterName }}
        - --configure-cloud-routes=true
        {{- include "cloud-controller-manager.featureGates" . | trimSuffix "," | indent 8 }}
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTP
            port: 10258
          successThreshold: 1
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
        ports:
        - containerPort: 10258
          name: metrics
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          name: kubeconfig
          readOnly: true
        - name: cloud-provider-config
          mountPath: /etc/kubernetes/cloudprovider
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kubeconfig
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: kubeconfig
                path: kubeconfig
              name: {{ .Values.global.genericTokenKubeconfigSecretName }}
              optional: false
          - secret:
              items:
              - key: token
                path: token
              name: shoot-access-cloud-controller-manager
              optional: false
      - name: cloud-provider-config
        secret:
          secretName: cloud-provider-config
