apiVersion: v1
kind: Secret
metadata:
  name: csi-diskplugin-alicloud
  namespace: kube-system
data:
  accessKeyID: {{ index .Values.credential.accessKeyID }}
  accessKeySecret: {{ index .Values.credential.accessKeySecret }}
  credentialsFile: {{ index .Values.credential.credentialsFile }}
type: Opaque
