replicas: 1
clusterName: shoot-foo-bar
podNetwork: 192.168.0.0/16
podAnnotations: {}
podLabels: {}
featureGates: {}
ccmNetworkFalg: public
images:
  alicloud-controller-manager: image-repository
resources:
  requests:
    cpu: 21m
    memory: 40Mi
cloudConfig: json-values
vpa: {}
