replicas: 1
clusterName: shoot-foo-bar
podNetwork: 192.168.0.0/16
podAnnotations: {}
podLabels: {}
featureGates: {}
  # RotateKubeletServerCertificate: false
images:
  alicloud-controller-manager: image-repository
resources:
  requests:
    cpu: 21m
    memory: 40Mi
  limits:
    memory: 1Gi
cloudConfig: json-values
vpa:
  resourcePolicy:
    maxAllowed:
      cpu: 4
      memory: 10G
